version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/logs
      - .:/app
    depends_on:
      - neo4j
      - minio

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data

  streamlit:
    build:
      context: .
    command: streamlit run streamlit_app/main.py --server.port=8501 --server.enableCORS=false
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/logs

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
